"""initial_schema

Revision ID: d4cf556a873d
Revises: 
Create Date: 2026-05-19 13:58:55.329633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4cf556a873d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('nickname', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_proxy', sa.Boolean(), nullable=False),
    sa.Column('invite_code', sa.String(length=32), nullable=True),
    sa.Column('activation_code', sa.String(length=10), nullable=True),
    sa.Column('activation_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('premium_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('family_voice_url', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_activation_code'), 'users', ['activation_code'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_invite_code'), 'users', ['invite_code'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('blood_pressure_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('systolic', sa.Integer(), nullable=False),
    sa.Column('diastolic', sa.Integer(), nullable=False),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blood_pressure_records_id'), 'blood_pressure_records', ['id'], unique=False)
    op.create_index(op.f('ix_blood_pressure_records_user_id'), 'blood_pressure_records', ['user_id'], unique=False)
    op.create_index('ix_blood_pressure_user_measured', 'blood_pressure_records', ['user_id', 'measured_at'], unique=False)
    op.create_table('blood_sugar_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Float(), nullable=False),
    sa.Column('condition', sa.String(length=64), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blood_sugar_records_id'), 'blood_sugar_records', ['id'], unique=False)
    op.create_index(op.f('ix_blood_sugar_records_user_id'), 'blood_sugar_records', ['user_id'], unique=False)
    op.create_index('ix_blood_sugar_user_measured', 'blood_sugar_records', ['user_id', 'measured_at'], unique=False)
    op.create_table('device_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fcm_token', sa.String(length=512), nullable=True),
    sa.Column('wxpusher_uid', sa.String(length=128), nullable=True),
    sa.Column('device_label', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_tokens_fcm_token'), 'device_tokens', ['fcm_token'], unique=False)
    op.create_index(op.f('ix_device_tokens_id'), 'device_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_device_tokens_user_id'), 'device_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_device_tokens_wxpusher_uid'), 'device_tokens', ['wxpusher_uid'], unique=False)
    op.create_table('family_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elder_id', sa.Integer(), nullable=False),
    sa.Column('caregiver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('permissions', sa.String(length=32), nullable=False),
    sa.Column('elder_alias', sa.String(length=128), nullable=True),
    sa.Column('caregiver_alias', sa.String(length=128), nullable=True),
    sa.Column('family_voice_url', sa.String(length=1024), nullable=True),
    sa.Column('family_voice_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['caregiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['elder_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_links_caregiver_id'), 'family_links', ['caregiver_id'], unique=False)
    op.create_index(op.f('ix_family_links_elder_id'), 'family_links', ['elder_id'], unique=False)
    op.create_index(op.f('ix_family_links_id'), 'family_links', ['id'], unique=False)
    op.create_table('medication_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('dosage', sa.String(length=256), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('times_a_day', sa.Text(), nullable=False),
    sa.Column('notify_missed', sa.Boolean(), nullable=False),
    sa.Column('notify_delay_minutes', sa.Integer(), nullable=False),
    sa.Column('voice_url', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_plans_id'), 'medication_plans', ['id'], unique=False)
    op.create_index(op.f('ix_medication_plans_user_id'), 'medication_plans', ['user_id'], unique=False)
    op.create_table('pro_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_user_id')
    )
    op.create_index(op.f('ix_pro_shares_id'), 'pro_shares', ['id'], unique=False)
    op.create_index(op.f('ix_pro_shares_owner_id'), 'pro_shares', ['owner_id'], unique=False)
    op.create_table('subscription_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('app_user_id', sa.String(length=128), nullable=True),
    sa.Column('revenuecat_event_id', sa.String(length=128), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('product_id', sa.String(length=256), nullable=True),
    sa.Column('entitlement_id', sa.String(length=128), nullable=True),
    sa.Column('transaction_id', sa.String(length=256), nullable=True),
    sa.Column('original_transaction_id', sa.String(length=256), nullable=True),
    sa.Column('store', sa.String(length=64), nullable=True),
    sa.Column('environment', sa.String(length=64), nullable=True),
    sa.Column('purchased_at_ms', sa.BigInteger(), nullable=True),
    sa.Column('expiration_at_ms', sa.BigInteger(), nullable=True),
    sa.Column('price', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=16), nullable=True),
    sa.Column('raw_event', sa.Text(), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_events_app_user_id'), 'subscription_events', ['app_user_id'], unique=False)
    op.create_index(op.f('ix_subscription_events_event_type'), 'subscription_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_subscription_events_id'), 'subscription_events', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_events_original_transaction_id'), 'subscription_events', ['original_transaction_id'], unique=False)
    op.create_index(op.f('ix_subscription_events_received_at'), 'subscription_events', ['received_at'], unique=False)
    op.create_index(op.f('ix_subscription_events_revenuecat_event_id'), 'subscription_events', ['revenuecat_event_id'], unique=False)
    op.create_index(op.f('ix_subscription_events_transaction_id'), 'subscription_events', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_subscription_events_user_id'), 'subscription_events', ['user_id'], unique=False)
    op.create_table('family_link_action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('elder_id', sa.Integer(), nullable=True),
    sa.Column('caregiver_id', sa.Integer(), nullable=True),
    sa.Column('link_id', sa.Integer(), nullable=True),
    sa.Column('counterpart_name', sa.String(length=128), nullable=True),
    sa.Column('invite_code', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['caregiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['elder_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['link_id'], ['family_links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_link_action_logs_action'), 'family_link_action_logs', ['action'], unique=False)
    op.create_index(op.f('ix_family_link_action_logs_actor_user_id'), 'family_link_action_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_family_link_action_logs_caregiver_id'), 'family_link_action_logs', ['caregiver_id'], unique=False)
    op.create_index(op.f('ix_family_link_action_logs_created_at'), 'family_link_action_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_family_link_action_logs_elder_id'), 'family_link_action_logs', ['elder_id'], unique=False)
    op.create_index(op.f('ix_family_link_action_logs_id'), 'family_link_action_logs', ['id'], unique=False)
    op.create_index(op.f('ix_family_link_action_logs_link_id'), 'family_link_action_logs', ['link_id'], unique=False)
    op.create_table('medication_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('taken_date', sa.Date(), nullable=False),
    sa.Column('taken_time', sa.Time(), nullable=False),
    sa.Column('is_taken', sa.Boolean(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['medication_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_logs_id'), 'medication_logs', ['id'], unique=False)
    op.create_index(op.f('ix_medication_logs_plan_id'), 'medication_logs', ['plan_id'], unique=False)
    op.create_index(op.f('ix_medication_logs_user_id'), 'medication_logs', ['user_id'], unique=False)
    op.create_table('medication_poke_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('caregiver_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['medication_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_poke_events_caregiver_id'), 'medication_poke_events', ['caregiver_id'], unique=False)
    op.create_index(op.f('ix_medication_poke_events_created_at'), 'medication_poke_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_medication_poke_events_id'), 'medication_poke_events', ['id'], unique=False)
    op.create_index(op.f('ix_medication_poke_events_plan_id'), 'medication_poke_events', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medication_poke_events_plan_id'), table_name='medication_poke_events')
    op.drop_index(op.f('ix_medication_poke_events_id'), table_name='medication_poke_events')
    op.drop_index(op.f('ix_medication_poke_events_created_at'), table_name='medication_poke_events')
    op.drop_index(op.f('ix_medication_poke_events_caregiver_id'), table_name='medication_poke_events')
    op.drop_table('medication_poke_events')
    op.drop_index(op.f('ix_medication_logs_user_id'), table_name='medication_logs')
    op.drop_index(op.f('ix_medication_logs_plan_id'), table_name='medication_logs')
    op.drop_index(op.f('ix_medication_logs_id'), table_name='medication_logs')
    op.drop_table('medication_logs')
    op.drop_index(op.f('ix_family_link_action_logs_link_id'), table_name='family_link_action_logs')
    op.drop_index(op.f('ix_family_link_action_logs_id'), table_name='family_link_action_logs')
    op.drop_index(op.f('ix_family_link_action_logs_elder_id'), table_name='family_link_action_logs')
    op.drop_index(op.f('ix_family_link_action_logs_created_at'), table_name='family_link_action_logs')
    op.drop_index(op.f('ix_family_link_action_logs_caregiver_id'), table_name='family_link_action_logs')
    op.drop_index(op.f('ix_family_link_action_logs_actor_user_id'), table_name='family_link_action_logs')
    op.drop_index(op.f('ix_family_link_action_logs_action'), table_name='family_link_action_logs')
    op.drop_table('family_link_action_logs')
    op.drop_index(op.f('ix_subscription_events_user_id'), table_name='subscription_events')
    op.drop_index(op.f('ix_subscription_events_transaction_id'), table_name='subscription_events')
    op.drop_index(op.f('ix_subscription_events_revenuecat_event_id'), table_name='subscription_events')
    op.drop_index(op.f('ix_subscription_events_received_at'), table_name='subscription_events')
    op.drop_index(op.f('ix_subscription_events_original_transaction_id'), table_name='subscription_events')
    op.drop_index(op.f('ix_subscription_events_id'), table_name='subscription_events')
    op.drop_index(op.f('ix_subscription_events_event_type'), table_name='subscription_events')
    op.drop_index(op.f('ix_subscription_events_app_user_id'), table_name='subscription_events')
    op.drop_table('subscription_events')
    op.drop_index(op.f('ix_pro_shares_owner_id'), table_name='pro_shares')
    op.drop_index(op.f('ix_pro_shares_id'), table_name='pro_shares')
    op.drop_table('pro_shares')
    op.drop_index(op.f('ix_medication_plans_user_id'), table_name='medication_plans')
    op.drop_index(op.f('ix_medication_plans_id'), table_name='medication_plans')
    op.drop_table('medication_plans')
    op.drop_index(op.f('ix_family_links_id'), table_name='family_links')
    op.drop_index(op.f('ix_family_links_elder_id'), table_name='family_links')
    op.drop_index(op.f('ix_family_links_caregiver_id'), table_name='family_links')
    op.drop_table('family_links')
    op.drop_index(op.f('ix_device_tokens_wxpusher_uid'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_user_id'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_id'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_fcm_token'), table_name='device_tokens')
    op.drop_table('device_tokens')
    op.drop_index('ix_blood_sugar_user_measured', table_name='blood_sugar_records')
    op.drop_index(op.f('ix_blood_sugar_records_user_id'), table_name='blood_sugar_records')
    op.drop_index(op.f('ix_blood_sugar_records_id'), table_name='blood_sugar_records')
    op.drop_table('blood_sugar_records')
    op.drop_index('ix_blood_pressure_user_measured', table_name='blood_pressure_records')
    op.drop_index(op.f('ix_blood_pressure_records_user_id'), table_name='blood_pressure_records')
    op.drop_index(op.f('ix_blood_pressure_records_id'), table_name='blood_pressure_records')
    op.drop_table('blood_pressure_records')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_invite_code'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_activation_code'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
