name: Deploy

on:
  push:
    branches: 
      - "main"

jobs:
  backend:
    name: Backend checks
    runs-on: ubuntu-latest
    
    steps:
      - name: 0. 获取最新代码
        uses: actions/checkout@v4
        
      - name: 1. 通过 SCP 将代码推送到你的云服务器
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "backend/,frontend/dist/,frontend/nginx.conf,docker-compose.yml"
          target: ${{ secrets.DEPLOY_PATH}}

      - name: 2. SSH 登录服务器并重启 Docker 容器
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # ▼ 核心修改 登录后进入正确的目录 ▼
            cd ${{ secrets.DEPLOY_PATH}}

            # 确保当前用户有权限操作 Docker
            echo ">>> 正在检查 Docker 权限..."
            docker ps > /dev/null 2>&1 || alias docker='sudo docker'

            docker compose down
            docker compose up -d --build
            echo ">>> 部署完成，系统已上线！"
